ALTER TABLE specimenTypes
  ADD COLUMN material VARCHAR(255) NULL,
  ADD COLUMN size VARCHAR(255) NULL,
  ADD COLUMN weight VARCHAR(255) NULL;

CREATE TABLE IF NOT EXISTS methods (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  description TEXT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS equipmentLoans (
  id INT AUTO_INCREMENT PRIMARY KEY,
  equipmentId INT NOT NULL,
  fromBranchId INT NOT NULL,
  toBranchId INT NOT NULL,
  loanDate DATE NOT NULL,
  expectedReturnDate DATE NULL,
  returnedAt DATETIME NULL,
  notes TEXT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS specimenLoans (
  id INT AUTO_INCREMENT PRIMARY KEY,
  specimenId INT NOT NULL,
  fromBranchId INT NOT NULL,
  toBranchId INT NOT NULL,
  loanDate DATE NOT NULL,
  expectedReturnDate DATE NULL,
  returnedAt DATETIME NULL,
  notes TEXT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
