CREATE TABLE qualityActions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  referenceNumber VARCHAR(60) NOT NULL UNIQUE,
  title VARCHAR(255) NOT NULL,
  category ENUM('Nonconformance', 'Corrective Action', 'Observation', 'Improvement') NOT NULL DEFAULT 'Nonconformance',
  source ENUM('Customer Complaint', 'Internal Audit', 'Supplier', 'Training', 'Examination', 'Level III', 'Equipment', 'Document Control', 'Management Review', 'Other') NOT NULL DEFAULT 'Other',
  severity ENUM('Minor', 'Major', 'Critical') NOT NULL DEFAULT 'Minor',
  status ENUM('Open', 'In Progress', 'Awaiting Verification', 'Closed') NOT NULL DEFAULT 'Open',
  branchId INT NULL,
  ownerName VARCHAR(255) NULL,
  reportedByUserId INT NULL,
  reportedDate DATE NOT NULL,
  dueDate DATE NULL,
  closedAt DATETIME NULL,
  description TEXT NOT NULL,
  immediateCorrection TEXT NULL,
  rootCause TEXT NULL,
  correctiveAction TEXT NULL,
  verificationNotes TEXT NULL,
  verifiedByName VARCHAR(255) NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
