CREATE TABLE IF NOT EXISTS `levelIIITechnicianCertificates` (
  `id` int AUTO_INCREMENT NOT NULL,
  `technicianId` int NOT NULL,
  `assessmentId` int DEFAULT NULL,
  `clientId` int NOT NULL,
  `clientBranchId` int DEFAULT NULL,
  `certificateNumber` varchar(120) NOT NULL,
  `method` varchar(255) NOT NULL,
  `level` varchar(100) NOT NULL,
  `methodLevels` json DEFAULT NULL,
  `issuedDate` date NOT NULL,
  `validUntil` date DEFAULT NULL,
  `validityValue` int DEFAULT NULL,
  `validityUnit` enum('days','months','years','custom') DEFAULT NULL,
  `status` enum('Active','Expired','Revoked','Superseded') NOT NULL DEFAULT 'Active',
  `fileName` varchar(255) DEFAULT NULL,
  `fileUrl` text DEFAULT NULL,
  `fileKey` varchar(500) DEFAULT NULL,
  `contentType` varchar(255) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `issuedBy` int DEFAULT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `levelIIITechnicianCertificates_id_pk` PRIMARY KEY (`id`),
  CONSTRAINT `levelIIITechnicianCertificates_certificateNumber_unique` UNIQUE (`certificateNumber`),
  KEY `levelIIITechnicianCertificates_technician_idx` (`technicianId`),
  KEY `levelIIITechnicianCertificates_assessment_idx` (`assessmentId`),
  KEY `levelIIITechnicianCertificates_client_idx` (`clientId`),
  KEY `levelIIITechnicianCertificates_validUntil_idx` (`validUntil`),
  KEY `levelIIITechnicianCertificates_status_idx` (`status`)
);
