ALTER TABLE users
  ADD COLUMN IF NOT EXISTS avatarUrl TEXT NULL;

ALTER TABLE branches
  ADD COLUMN IF NOT EXISTS companyName VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS companyDescription TEXT NULL,
  ADD COLUMN IF NOT EXISTS logoUrl TEXT NULL,
  ADD COLUMN IF NOT EXISTS primaryColor VARCHAR(7) NULL,
  ADD COLUMN IF NOT EXISTS secondaryColor VARCHAR(7) NULL;

ALTER TABLE documents
  ADD COLUMN IF NOT EXISTS content TEXT NULL;
